### ISSUE TITLE
xNFT preview API broken

### ISSUE THREAD

**Issue by callensm** [coral-xyz/backpack#2132]
Recently starting throwing this error for all xNFTs on the current deployment of https://xnft.gg

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at j2 (popup.js:147:168040)
    at AA (popup.js:2:2197674)
    at ja (popup.js:2:2249723)
    at ks (popup.js:2:2236997)
    at Cs (popup.js:2:2236925)
    at vs (popup.js:2:2236788)
    at gs (popup.js:2:2233775)
    at popup.js:2:2183596
    at t.unstable_runWithPriority (popup.js:2:2277321)
    at ji (popup.js:2:2183373)
aa @ popup.js:2
background.js:2 error fetching: https://data.mysteryboxis.com/mysteryboxis_com.json TypeError: Failed to fetch
    at t (background.js:2:2100145)
    at new Promise (<anonymous>)
    at background.js:2:2100059
    at Array.map (<anonymous>)
    at background.js:2:2099981
    at Ao (background.js:2:2100471)
    at async background.js:2:2639372
```

**Comment by armaniferrante** [comment]
Appears this is only a problem with the chrome store build and has been fixed on master.
