### ISSUE TITLE
yarn install issue

### ISSUE THREAD

**Issue by Haniamin90** [coral-xyz/backpack#3231]
![image](https://user-images.githubusercontent.com/107732507/223647139-9bdc0267-e835-44c4-b561-83836321872b.png)

**Comment by x0samnan** [comment]
@Haniamin90 
Try this:
```
> rm -rf node_modules
> yarn cache clean
> yarn
```

**Comment by x0samnan** [comment]
@Haniamin90 
Try this:
```
> rm -rf node_modules
> yarn cache clean
> yarn
```

**Comment by jayam04** [comment]
I am also facing issue with `yarn install`, it exits with error code 1
error occurs at `backpack@workspace can't be build`
I am using `ubuntu` machine

![Screenshot from 2023-03-09 22-35-38](https://user-images.githubusercontent.com/93824505/224102543-01f00fd2-a15d-431d-a65c-b5c282994ca8.png)

![image](https://user-images.githubusercontent.com/93824505/224102785-621b1247-a3a2-4d10-ac4f-cae6abc13fe4.png)

**logs**
### This file contains the result of Yarn building a package (backpack@workspace:.)
### Script name: postinstall

```
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at parseYarnLock (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/index.js:7:42)
    at fixDuplicates (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/index.js:123:18)
    at Object.<anonymous> (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/cli.js:52:60)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

```

**Comment by jayam04** [comment]
This issue can be fixed using `yarn v1` as given in issue #3275
