### ISSUE TITLE
I am also facing issue with `yarn install`, it exits with error code 1

### ISSUE THREAD

**Issue by jayam04** [coral-xyz/backpack#3275]
I am also facing issue with `yarn install`, it exits with error code 1
error occurs at `backpack@workspace can't be build`
I am using `ubuntu` machine

![Screenshot from 2023-03-09 22-35-38](https://user-images.githubusercontent.com/93824505/224102543-01f00fd2-a15d-431d-a65c-b5c282994ca8.png)

![image](https://user-images.githubusercontent.com/93824505/224102785-621b1247-a3a2-4d10-ac4f-cae6abc13fe4.png)

**logs**
### Script name: postinstall

```
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/home/jayam/CodeHub/projects/backpack/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at parseYarnLock (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/index.js:7:42)
    at fixDuplicates (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/index.js:123:18)
    at Object.<anonymous> (/home/jayam/CodeHub/projects/backpack/node_modules/yarn-deduplicate/dist/cli.js:52:60)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

```

_Originally posted by @jayam04 in https://github.com/coral-xyz/backpack/issues/3231#issuecomment-1462440669_
#3231

I have recreated issue as original is not getting reviewed even after I added my issue in comments. If I shouldn't have recreated this I apologize but I can't start developing without packages not being installed.

**Comment by jayam04** [comment]
please let me know if any other information is needed

**Comment by wentokay** [comment]
which version of yarn are you using?

```
yarn -v

1.22.19
```

we're currently using v1 on this project

**Comment by wentokay** [comment]
sure, it's surprising that newer versions of yarn ignore this https://github.com/coral-xyz/backpack/blob/2bddc21b5dc56a207c683cd8483e9744313ddb1f/package.json#L78

**Comment by wentokay** [comment]
related https://github.com/yarnpkg/yarn/issues/2800#issuecomment-1305771298
