### ISSUE TITLE
Code 129 Error while building with yarn

### ISSUE THREAD

**Issue by iamkalio** [coral-xyz/backpack#4317]
Here is an image of my terminal log 
<img width="1148" alt="Screenshot 2024-05-30 at 14 42 46" src="https://github.com/coral-xyz/backpack/assets/89003403/b8b30972-9671-45c5-8267-221f0eae537f">

**Comment by iamkalio** [comment]
`% yarn build
• Packages in scope: @coral-xyz/app-extension, @coral-xyz/background, @coral-xyz/backpack-web, @coral-xyz/common, @coral-xyz/data-components, @coral-xyz/expo-devtools, @coral-xyz/i18n, @coral-xyz/provider-core, @coral-xyz/provider-injection, @coral-xyz/react-common, @coral-xyz/recoil, @coral-xyz/secure-background, @coral-xyz/secure-clients, @coral-xyz/secure-ui, @coral-xyz/staking, @coral-xyz/tamagui, @coral-xyz/wallet-standard, @coral-xyz/xnft-cli, eslint-config-custom
• Running build in 19 packages
• Remote caching disabled
@coral-xyz/backpack-web:build: cache hit, replaying logs 72fa53e61c31bb8a
@coral-xyz/expo-devtools:build: cache hit, replaying logs 439be52a651fb8e2
@coral-xyz/wallet-standard:build: cache hit, replaying logs 8d9ba2588e11467e
@coral-xyz/common:build: cache hit, replaying logs 1193f27f2e7207bb
@coral-xyz/backpack-web:build: info  - Skipping validation of types
@coral-xyz/backpack-web:build: info  - Linting...
@coral-xyz/backpack-web:build: 
@coral-xyz/backpack-web:build: ./pages/downloads.tsx
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: > @coral-xyz/wallet-standard@0.1.0 clean
@coral-xyz/wallet-standard:build: > shx mkdir -p lib && shx rm -rf lib
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: > @coral-xyz/wallet-standard@0.1.0 tsc
@coral-xyz/wallet-standard:build: > tsc --build --verbose tsconfig.all.json
@coral-xyz/backpack-web:build: 45:1  Warning: This line has a length of 119. Maximum allowed is 100.  max-len
@coral-xyz/backpack-web:build: 
@coral-xyz/backpack-web:build: ./components/Nav.tsx
@coral-xyz/backpack-web:build: 63:1  Warning: This line has a length of 109. Maximum allowed is 100.  max-len
@coral-xyz/backpack-web:build: 66:1  Warning: This line has a length of 148. Maximum allowed is 100.  max-len
@coral-xyz/backpack-web:build: 
@coral-xyz/backpack-web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
@coral-xyz/backpack-web:build: info  - Creating an optimized production build...
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 3:46:15 PM - Projects in this build: 
@coral-xyz/wallet-standard:build:     * tsconfig.cjs.json
@coral-xyz/wallet-standard:build:     * tsconfig.esm.json
@coral-xyz/wallet-standard:build:     * tsconfig.all.json
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 3:46:15 PM - Project 'tsconfig.cjs.json' is out of date because output file 'lib/cjs/account.js' does not exist
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 3:46:15 PM - Building project '/Users/princewillkalio/codes/backpack/packages/wallet-standard/tsconfig.cjs.json'...
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 3:46:16 PM - Project 'tsconfig.esm.json' is out of date because output file 'lib/esm/account.js' does not exist
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 3:46:16 PM - Building project '/Users/princewillkalio/codes/backpack/packages/wallet-standard/tsconfig.esm.json'...
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: 
@coral-xyz/wallet-standard:build: > @coral-xyz/wallet-standard@0.1.0 package
@coral-xyz/wallet-standard:build: > shx mkdir -p lib/cjs && shx echo '{ "type": "commonjs" }' > lib/cjs/package.json
@coral-xyz/wallet-standard:build: 
@coral-xyz/i18n:build: cache hit, replaying logs 674aae0a6c2ddb41
@coral-xyz/secure-background:build: cache hit, replaying logs 0c6a1be6ae523229
@coral-xyz/secure-clients:build: cache hit, replaying logs 5455dc023c947ff0
@coral-xyz/recoil:build: cache miss, executing 05549b4e6e4bdb84
@coral-xyz/provider-core:build: cache hit, replaying logs 80bda488073039e8
@coral-xyz/background:build: cache hit, replaying logs 69c7eaadb72b7ff8
@coral-xyz/provider-injection:build: cache hit, replaying logs 4778dd707dae0918
@coral-xyz/provider-injection:build: built provider-injection, with 0 errors
@coral-xyz/recoil:build: [STARTED] Parse Configuration
@coral-xyz/recoil:build: [SUCCESS] Parse Configuration
@coral-xyz/recoil:build: [STARTED] Generate outputs
@coral-xyz/recoil:build: [STARTED] Generate to ./src/apollo/
@coral-xyz/recoil:build: [STARTED] Load GraphQL schemas
@coral-xyz/recoil:build: [SUCCESS] Load GraphQL schemas
@coral-xyz/recoil:build: [STARTED] Load GraphQL documents
@coral-xyz/recoil:build: [SUCCESS] Load GraphQL documents
@coral-xyz/recoil:build: [STARTED] Generate
@coral-xyz/recoil:build: [FAILED] GraphQL Document Validation failed with 2 errors;
@coral-xyz/recoil:build: [FAILED]   Error 0: Cannot query field "jupiterSwapValidInputTokens" on type "Query".
@coral-xyz/recoil:build: [FAILED]     at /Users/princewillkalio/codes/backpack/packages/recoil/src/context/Swap/hooks.ts:3:7
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [FAILED] Error 1: Cannot query field "jupiterSwapOutputTokens" on type "Query". Did you mean "jupiterTradableTokens"?
@coral-xyz/recoil:build: [FAILED]     at /Users/princewillkalio/codes/backpack/packages/recoil/src/context/Swap/hooks.ts:3:5
@coral-xyz/recoil:build: [SUCCESS] Generate outputs
@coral-xyz/recoil:build: ERROR: command finished with error: command (/Users/princewillkalio/codes/backpack/packages/recoil) /private/var/folders/bk/1cbrq18156v_djt2z9db3hkr0000gn/T/xfs-fc2c30b7/yarn run build exited (1)
@coral-xyz/recoil#build: command (/Users/princewillkalio/codes/backpack/packages/recoil) /private/var/folders/bk/1cbrq18156v_djt2z9db3hkr0000gn/T/xfs-fc2c30b7/yarn run build exited (1)

 Tasks:    10 successful, 11 total
Cached:    10 cached, 11 total
  Time:    8.524s 
Failed:    @coral-xyz/recoil#build

 ERROR  run failed: command  exited (1)`

**Comment by sndmndss** [comment]
Hey,
1. Try to run this and then one more time to build:
```
yarn clean
```

2. Try to clone repo to other dir and try there, maybe something is damaged.

**Comment by sndmndss** [comment]
nvm, I think the problem is that API was changed, but code - no.

**Comment by iamkalio** [comment]
SO how do i resolve it? change the API?

**Comment by sndmndss** [comment]
> SO how do i resolve it? change the API?

Just shared it with team. Wait for the response.

**Comment by Aditya-040** [comment]
can i work on it

**Comment by sndmndss** [comment]
Devs will update this repo ASAP. Stay tuned.

**Comment by pepeneif** [comment]
> can i work on it

Hi Aditya, how can we help you or motivate you to work on this?

**Comment by Auspxe** [comment]
@hkirat Hi I am tagging you to this to see if you can be of any help?

**Comment by Yn2o** [comment]
Very complete thank you

**Comment by Abhinavreddy733** [comment]
@hkirat i got the same issue when i am setting up in local , would u please help me to fix the issue

**Comment by sndmndss** [comment]
@Abhinavreddy733 This repository hasn’t been updated in 10 months, and the API endpoints have changed since then. We might update it at some point in the future.

**Comment by Abhinavreddy733** [comment]
@sndmndss then how can we contribute for this repo

**Comment by sndmndss** [comment]
@Abhinavreddy733 contributing is impossible atm.

**Comment by indranildeveloper** [comment]
Are there any updates of this? not able to set up locally.
