### ISSUE TITLE
"ERR_INVALID_ARG_TYPE" Error during build.

### ISSUE THREAD

**Issue by fantarics** [coral-xyz/backpack#4350]
```@coral-xyz/recoil:build: [STARTED] Parse Configuration
@coral-xyz/recoil:build: [SUCCESS] Parse Configuration
@coral-xyz/recoil:build: [STARTED] Generate outputs
@coral-xyz/recoil:build: [STARTED] Generate to ./src/apollo/
@coral-xyz/recoil:build: [STARTED] Load GraphQL schemas
@coral-xyz/provider-injection:build: cache miss, executing 4778dd707dae0918
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [FAILED]         Failed to load schema from https://backpack-api.xnfts.dev/v2/graphql:
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [SUCCESS] Generate outputs
@coral-xyz/recoil:build: [FAILED]         Could not obtain introspection result, received the following as response; 
@coral-xyz/recoil:build: [FAILED]  { code: "ERR_INVALID_ARG_TYPE" }
@coral-xyz/recoil:build: [FAILED]         GraphQLError: Could not obtain introspection result, received the following as response; 
@coral-xyz/recoil:build: [FAILED]  { code: "ERR_INVALID_ARG_TYPE" }
@coral-xyz/recoil:build: [FAILED]     at createGraphQLError (/Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)
@coral-xyz/recoil:build: [FAILED]     at getSchemaFromIntrospection (/Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/wrap/cjs/introspect.js:21:42)
@coral-xyz/recoil:build: [FAILED]     at /Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/wrap/cjs/introspect.js:44:32
@coral-xyz/recoil:build: [FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@coral-xyz/recoil:build: [FAILED]     at async UrlLoader.load (/Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/url-loader/cjs/index.js:220:29)
@coral-xyz/recoil:build: [FAILED]     at async /Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
@coral-xyz/recoil:build: [FAILED]     at async Promise.all (index 5)
@coral-xyz/recoil:build: [FAILED]     at async loadFile (/Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
@coral-xyz/recoil:build: [FAILED]     at async /Users/addlyy/Desktop/backpack/backpack/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:229:25
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [FAILED]         GraphQL Code Generator supports:
@coral-xyz/recoil:build: [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
@coral-xyz/recoil:build: [FAILED]           - Introspection JSON File
@coral-xyz/recoil:build: [FAILED]           - URL of GraphQL endpoint
@coral-xyz/recoil:build: [FAILED]           - Multiple files with type definitions (glob expression)
@coral-xyz/recoil:build: [FAILED]           - String in config file
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [FAILED]         Try to use one of above options and run codegen again.
@coral-xyz/recoil:build: [FAILED] 
@coral-xyz/recoil:build: [FAILED]       
```

To replicate clone the repo, yarn install -> yarn build, then this error pops up.
The issue is that https://backpack-api.xnfts.dev/v2/graphql does not provide any data, the path seems to be outdated for building

**Comment by dhunganasaroj3** [comment]
This issue also appears on `yarn start`

**Comment by roman-syrota** [comment]
same issue :(

**Comment by powerbrake** [comment]
Same issue
