### ISSUE TITLE
Building fails with error: Invalid argument: MDB_BAD_RSLOT

### ISSUE THREAD

**Issue by colinlgray** [coral-xyz/backpack#894]
When I run `yarn build` I receive this error:

```
@coral-xyz/example-client:build: 🚨 Build failed.
@coral-xyz/example-client:build:
@coral-xyz/example-client:build: Error: Invalid argument: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot: The reader lock pid 8047, txn -1, doesn't match env pid 7649
@coral-xyz/example-client:build:
@coral-xyz/example-client:build:   Error: Invalid argument: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot: The reader lock pid 8047, txn -1, doesn't match env pid 7649
@coral-xyz/example-client:build:       at LMDBStore.getBinaryFast (/home/cgray/repos/backpack/node_modules/lmdb/dist/index.cjs:1443:12)
@coral-xyz/example-client:build:       at LMDBStore.getBinary (/home/cgray/repos/backpack/node_modules/lmdb/dist/index.cjs:1524:27)
@coral-xyz/example-client:build:       at LMDBStore.get (/home/cgray/repos/backpack/node_modules/lmdb/dist/index.cjs:1537:17)
@coral-xyz/example-client:build:       at LMDBCache.get (/home/cgray/repos/backpack/node_modules/@parcel/cache/lib/LMDBCache.js:107:27)
@coral-xyz/example-client:build:       at Transformation.readFromCache (/home/cgray/repos/backpack/node_modules/@parcel/core/lib/Transformation.js:464:43)
@coral-xyz/example-client:build:       at Transformation.runPipelines (/home/cgray/repos/backpack/node_modules/@parcel/core/lib/Transformation.js:264:40)
@coral-xyz/example-client:build:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
@coral-xyz/example-client:build:       at async Transformation.run (/home/cgray/repos/backpack/node_modules/@parcel/core/lib/Transformation.js:183:21)
@coral-xyz/example-client:build:       at async Child.handleRequest (/home/cgray/repos/backpack/node_modules/@parcel/workers/lib/child.js:216:9)
@coral-xyz/example-client:build:
```

I tried running `yarn clean` and get the same error each time

Has anyone seen this before or have reccomendations on how to troubleshoot it? I'm running ubuntu on WSL and am on commit `ebbc4c331ecf35687cb1a8dab6de95c7569bab46`

**Comment by armaniferrante** [comment]
I have not seen this. Sounds related to your setup?

**Comment by armaniferrante** [comment]
Going to close this to keep github tidy. Let's move this to discord.
